### ISSUE TITLE
non-existent core rules and contribution link

### ISSUE THREAD

**Issue by ta2edchimp** [jfmengels/eslint-rule-documentation#1]
When specifying a non-existent core rule, a link to a non-existent page will be generated, e.g.

``` JavaScript
getRuleURI('foo-bar');
// => { found: true, url: 'http://eslint.org/docs/rules/foo-bar' }
```

Would it be viable to use `eslint-find-rule` (as a lib) or just use similar means to check if there's an actual rule by that name and print a help otherwise?

**Comment by Arcanemagus** [comment]
How would a non-existent core rule ever be thrown in a message?

The only way I can think of is if the user is using a severely out of date `eslint`, and I don't know about @jfmengels, but that's not something that is really worth supporting in my opinion.

As for `eslint-find-rules`, that requires a config file path to be fed to it, this library is meant to only be given a rule name and return a URL if one is known.

**Comment by jfmengels** [comment]
> that's not something that is really worth supporting in my opinion

Same here. We'll see that if some case arises that we didn't think of. For now, this is fine IMO.

@ta2edchimp did you ever come against such a situation, or is it just hypothetical?

**Comment by ta2edchimp** [comment]
I had such a situation in a unit test for `eslint-find-rules` today.
While that was a completely made up situation, that we should handle on that module's end, I was just curious what you guys think how this should be handled — or whether at all, atm.

**Comment by jfmengels** [comment]
I'll close this for now, but please leave a comment if you find an actual problem with this.
